image: ruby:2.3

test:
  stage: test
  script:
  - bundle
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle
  - bundle exec jekyll build -d public
  - cp ./public/.well-known/acme-challenge/L1_OTuTgE_VhmqwvShP9WbFsrREG2Wcu5YLf6eLMgYk.html ./public/.well-known/acme-challenge/L1_OTuTgE_VhmqwvShP9WbFsrREG2Wcu5YLf6eLMgYk
  artifacts:
    paths:
    - public
  only:
  - master
